[package]
name = "ccwc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
indexmap = "2.6.0"

[dev-dependencies]
tempfile = "3.14.0"
